### PR TITLE
Cards- in progress

### PR DESCRIPTION
**Pull request by aspriggle**

### CODE REVIEW

**Review by toddvharper — APPROVED** [review]
Looks good! I'll plan to implement the activity card on the itinerary page this evening, so we can see what it looks like on the rendered site :)

**Comment by toddvharper** [comment]
(knowing full well that you'll continue to make changes to it)

**Comment by toddvharper** [comment]
@JashonMenya I imagine the "All checks have failed" error is related to the tests you implemented?

**Comment by JashonMenya** [comment]
that's correct. Wrapped up the test and merging the PR

**Review by JashonMenya — APPROVED** [review]
that is correct. Current just failing cause we've not merged any tests in dev. Doing that rn

**Pull request merged**
